[fetch] add --fetch subcommand
facebook/dotslash pull request #20
Opened 2024-03-19 17:21 UTC by bolinfest

[fetch] add --fetch subcommand

2024-03-19 17:27 UTC, bolinfest commented
If we agree with this general direction, I can also update https://dotslash-cli.com/docs/flags/#experimental-commands as part of this PR.

2024-04-02 20:43 UTC, zertosh requested changes

2024-04-02 20:43 UTC, zertosh commented on src/subcommand.rs
> +            }
How do you feel about this? Stdout always just dumps the path (for easy parsing), and stderr tells you if it was downloaded or not. Or even even just doesn't tell you if it was downloaded.

```suggestion
            if !artifact_location.executable.exists() {
                let provider_factory = DefaultProviderFactory {};
                download_artifact(&artifact_entry, &artifact_location, &provider_factory)?;
                eprintln!("Downloaded artifact");
            } else {
                eprintln!("Artifact already exists");
            }
            println!("{}", artifact_location.executable.display());
```

2024-04-02 21:01 UTC, bigfootjon commented
(I'm going to hold up releasing a new version with zip support until this PR is resolved)

2024-04-09 16:14 UTC, bolinfest commented on src/subcommand.rs
> +            }
Sounds good to me! I suppose if we wanted to get really fancy, we could have JSON output that reports both pieces of information, but that's probably unnecessary and what you have is convenient for what I agree will be the common use case.

2024-04-10 13:46 UTC, zertosh commented on src/subcommand.rs
> +            }
Great! I'll make these changes and land

2024-04-10 16:25 UTC, closed without merging